### ISSUE TITLE
Submit Feed Reader Testing 

### ISSUE THREAD

**Issue by rudimusmaximus** [rudimusmaximus/FENDp4#2]
**_objective / purpose_**  

**_completion checklist_**
- [x] Changes Listed  (mark each member as completed update as needed)
  - [x] Download the [required project assets](http://github.com/udacity/frontend-nanodegree-feedreader).  
  - [x] Review the functionality of the application within your browser.  
  - [x] Explore the application's HTML (**./index.html**), CSS (**./css/style.css**) and JavaScript (**./js/app.js**) to gain an understanding of how it works.  
  - [x] Explore the Jasmine spec file in **./jasmine/spec/feedreader.js** and review the [Jasmine documentation](http://jasmine.github.io).  
  - [x] Edit the `allFeeds` variable in **./js/app.js** to make the provided test fail and see how Jasmine visualizes this failure in your application.  
  - [x] Return the `allFeeds` variable to a passing state.  
  - [x] Write a test that loops through each feed in the `allFeeds` object and ensures it has a URL defined and that the URL is not empty.  
  - [x] Write a test that loops through each feed in the `allFeeds` object and ensures it has a name defined and that the name is not empty.  
  - [x] Write a new test suite named `"The menu"`.  
  - [x] Write a test that ensures the menu element is hidden by default. You'll have to analyze the HTML and the CSS to determine how we're performing the hiding/showing of the menu element.  
  - [x] Write a test that ensures the menu changes visibility when the menu icon is clicked. This test should have two expectations: does the menu display when clicked and does it hide when clicked again.
  - [x] Write a test suite named `"Initial Entries"`.
  - [x] Write a test that ensures when the `loadFeed` function is called and completes its work, there is at least a single `.entry` element within the `.feed` container.
  - [x] Write a test suite named `"New Feed Selection"`.
  - [x] Write a test that ensures when a new feed is loaded by the `loadFeed` function that the content actually changes.
  - [x] No test should be dependent on the results of another.
  - [x] Callbacks should be used to ensure that feeds are loaded before they are tested.
  - [x] Implement error handling for undefined variables and out-of-bound array access. Included in loadFeed (review)
  - [x] When complete - all of your tests should pass. 
  - [x] Write a README file detailing all steps required to successfully run the application. If you have added additional tests (for Udacious Test Coverage),  provide documentation for what these future features are and what the tests are checking for.  
- [x] Developer Tested - Test Copies (Disposable Alpha "DA!s" and Release Candidate)

POST LIVE:
- [x] Works on mobile and tablets - works as instructed on chrome os, but not on ios phone. Mobile not a requirement of this project, so N/A
- [ ] Accepted by Udacity reviewer

**_full pipeline documentation_**
---
# Overview - describe with history and related items  
# Solution Design  
Course requirements Feed Reader Testing [Project Rubric](https://review.udacity.com/#!/projects/3442558598/rubric)

# What's New Entry  
n/a
# Solution Implementation Notes  
 - [x] Add instructions in case browser blocks loading.
